---
argument_specs:
  main:
    short_description: Configure k3s cluster
    options:
      apiserver_endpoint:
        description: Virtual ip-address configured on each master
        required: true

      bpf_lb_algorithm:
        description: BPF lb algorithm
        default: maglev

      bpf_lb_mode:
        description: BPF lb mode
        default: hybrid

      cilium_bgp:
        description:
          - Enable cilium BGP control plane for LB services and pod cidrs.
        type: bool
        default: false

      cilium_bgp_my_asn:
        description: Local ASN for BGP peer
        type: int
        default: 64513

      cilium_bgp_peer_asn:
        description: BGP peer ASN
        type: int
        default: 64512

      cilium_bgp_peer_address:
        description: BGP peer address
        default: ~

      cilium_bgp_neighbors:
        description: List of BGP peer ASN & address pairs
        default: []

      cilium_bgp_neighbors_groups:
        description: Inventory group in which to search for additional cilium_bgp_neighbors parameters to merge.
        default: ['k3s_all']

      cilium_bgp_lb_cidr:
        description: BGP load balancer IP range
        default: 192.168.31.0/24

      cilium_exportPodCIDR:
        description: Export pod CIDR
        type: bool
        default: true

      cilium_hubble:
        description: Enable Cilium Hubble
        type: bool
        default: true

      cilium_hubble_cli:
        description: Enable Cilium Hubble CLI
        type: bool
        default: true

      cilium_hubble_cli_version:
        description: Version of Cilium Hubble CLI to install
        default: v1.17.5

      cilium_iface:
        description: The network interface used for when Cilium is enabled
        default: ~

      cilium_mode:
        description: Inner-node communication mode
        default: tunnel
        choices:
          - native
          - tunnel

      cluster_cidr:
        description: Inner-cluster IP range
        default: 10.52.0.0/16

      enable_bpf_masquerade:
        description: Use IP masquerading
        type: bool
        default: true

      group_name_master:
        description: Name of the master group
        default: master

      kube_proxy_replacement:
        description: Replace the native kube-proxy with Cilium
        type: bool
        default: true

      kube_vip_lb_ip_range:
        description: IP range for kube-vip load balancer
        default: ~
