---
k3s_kubectl_binary: k3s kubectl

bpf_lb_algorithm: maglev
bpf_lb_mode: hybrid

cilium_bgp: false
cilium_exportPodCIDR: true  # noqa var-naming
cilium_bgp_my_asn: 64513
cilium_bgp_peer_asn: 64512
cilium_bgp_neighbors: []
cilium_bgp_neighbors_groups: ['k3s_all']
cilium_bgp_lb_cidr: 192.168.31.0/24
cilium_hubble: true
cilium_hubble_cli: true
cilium_hubble_cli_version: v1.17.5
cilium_mode: native
cilium_direct_routing_skip_unreachable: true

cluster_cidr: 10.52.0.0/16
enable_bpf_masquerade: true
kube_proxy_replacement: true
group_name_master: master
